##############################################################
# Learning Module: Vagrant Up for Network Envineers
# Lab: Using the Ansible Provisioner with Vagrant
# Author: Hank Preston <hapresto@cisco.com>
#
# ansible_provision.yaml
# Illustrate the following concepts:
# - Basic Playbook Structure for NX-OS Modules
# - Customizations to support Vagrant Devices
##############################################################
---
- name: Provision NX-OS Devices
  hosts: vagrant
  connection: local
  gather_facts: false

  tasks:
    - name: Pause to complete boot
      pause:
        seconds: 5

    - name: Enable NX-API
      nxos_feature:
        provider: "{{provider_ssh}}"
        feature: nxapi
        state: enabled

    - name: Configure System Settings
      nxos_system:
        provider: "{{provider_nxapi}}"
        hostname: "{{ inventory_hostname }}"

    - name: Configure Interfaces
      with_items: "{{ interfaces }}"
      nxos_interface:
        provider: "{{provider_nxapi}}"
        interface: "{{ item.name }}"
        mode: layer3
        description: "{{ item.desc }}"
        admin_state: up

    - name: Configure IPv4 Address on Interface
      with_items: "{{ interfaces }}"
      nxos_ip_interface:
        provider: "{{provider_nxapi}}"
        interface: "{{ item.name }}"
        version: v4
        addr: "{{ item.ip_address }}"
        mask: "{{ item.prefix }}"
