# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "nxos1" do |node|
        node.vm.box =  "nxos/7.0.3.I6.1"

        # Statically set the SSH port
        config.vm.network :forwarded_port, guest: 22, host: 2222, id: 'ssh', auto_correct: true
    end

    # Setup Ansible Provisioning
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible_provision.yaml"
      ansible.inventory_path = "./hosts"
      ansible.raw_arguments = ["--connection=paramiko"]
    end
end
