# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "nxos1" do |node|
        node.vm.box =  "nxos/7.0.3.I7.3"

        # Statically set the SSH and HTTP ports
        config.vm.network :forwarded_port, guest: 22, host: 2222, id: 'ssh', auto_correct: true
        config.vm.network :forwarded_port, guest: 80, host: 2224, id: 'http'
    end

    config.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "4096"
      vb.customize ['modifyvm', :id, '--uart1', '0x3F8', 4, '--uartmode1', 'disconnected']
      vb.customize ['modifyvm', :id, '--uart2', '0x2F8', 3, '--uartmode2', 'disconnected']
    end

    # Setup Ansible Provisioning
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible_provision.yaml"
      ansible.inventory_path = "./hosts"
      ansible.raw_arguments = ["--connection=paramiko"]
    end
end
